# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.2.0'

gem 'graphql', '~> 1.13.25'
gem 'graphql-schema_directives', '~> 0.0.2'
gem 'rack', '~> 2.2.24'
gem 'webrick', '~> 1.9.2'